apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: db-service
    app: demo-store-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
     name: mariadb-pod
     app: demo-store-app